# Generated by Django 3.1 on 2020-10-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In-Progress', 'In-Progress'), ('Done', 'Done')], default='In-Progress', max_length=12),
        ),
    ]
